[2024-02-21 06:17:19,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.run_python_script manual__2024-02-21T06:17:17.417892+00:00 [queued]>
[2024-02-21 06:17:19,384] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: csv_transformation_and_class_creation.run_python_script manual__2024-02-21T06:17:17.417892+00:00 [queued]>
[2024-02-21 06:17:19,385] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 06:17:19,385] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-21 06:17:19,385] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-21 06:17:19,395] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_python_script> on 2024-02-21 06:17:17.417892+00:00
[2024-02-21 06:17:19,399] {standard_task_runner.py:52} INFO - Started process 4400 to run task
[2024-02-21 06:17:19,402] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'csv_transformation_and_class_creation', 'run_python_script', 'manual__2024-02-21T06:17:17.417892+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmpy29sehjw', '--error-file', '/tmp/tmpu75q7ovw']
[2024-02-21 06:17:19,403] {standard_task_runner.py:80} INFO - Job 88: Subtask run_python_script
[2024-02-21 06:17:19,444] {task_command.py:369} INFO - Running <TaskInstance: csv_transformation_and_class_creation.run_python_script manual__2024-02-21T06:17:17.417892+00:00 [running]> on host 7f99983bc7dc
[2024-02-21 06:17:19,496] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=csv_transformation_and_class_creation
AIRFLOW_CTX_TASK_ID=run_python_script
AIRFLOW_CTX_EXECUTION_DATE=2024-02-21T06:17:17.417892+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-21T06:17:17.417892+00:00
[2024-02-21 06:17:19,578] {logging_mixin.py:115} INFO - jsjsjsjsj
[2024-02-21 06:17:19,578] {logging_mixin.py:115} INFO - Standard Output:
[2024-02-21 06:17:19,578] {logging_mixin.py:115} INFO - Standard Error:
[2024-02-21 06:17:19,579] {logging_mixin.py:115} INFO - python: can't open file 'models.py': [Errno 2] No such file or directory
[2024-02-21 06:17:19,579] {python.py:173} INFO - Done. Returned value was: None
[2024-02-21 06:17:19,591] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=csv_transformation_and_class_creation, task_id=run_python_script, execution_date=20240221T061717, start_date=20240221T061719, end_date=20240221T061719
[2024-02-21 06:17:19,625] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-21 06:17:19,647] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
