[2024-03-27 19:30:14,086] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bigdag.clean_task 0f396986-b3a0-406c-9ce7-b779ab334115 [queued]>
[2024-03-27 19:30:14,096] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: bigdag.clean_task 0f396986-b3a0-406c-9ce7-b779ab334115 [queued]>
[2024-03-27 19:30:14,096] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 19:30:14,097] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-03-27 19:30:14,097] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-27 19:30:14,118] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): clean_task> on 2024-03-27 19:29:04.110149+00:00
[2024-03-27 19:30:14,136] {standard_task_runner.py:52} INFO - Started process 1540 to run task
[2024-03-27 19:30:14,150] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'bigdag', 'clean_task', '0f396986-b3a0-406c-9ce7-b779ab334115', '--job-id', '1396', '--raw', '--subdir', 'DAGS_FOLDER/dags.py', '--cfg-path', '/tmp/tmplgx2isya', '--error-file', '/tmp/tmpl1t_dzcu']
[2024-03-27 19:30:14,158] {standard_task_runner.py:80} INFO - Job 1396: Subtask clean_task
[2024-03-27 19:30:14,237] {task_command.py:369} INFO - Running <TaskInstance: bigdag.clean_task 0f396986-b3a0-406c-9ce7-b779ab334115 [running]> on host 9b878320bbfc
[2024-03-27 19:30:14,307] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bigdag
AIRFLOW_CTX_TASK_ID=clean_task
AIRFLOW_CTX_EXECUTION_DATE=2024-03-27T19:29:04.110149+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=0f396986-b3a0-406c-9ce7-b779ab334115
[2024-03-27 19:30:14,312] {python.py:173} INFO - Done. Returned value was: None
[2024-03-27 19:30:14,331] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=bigdag, task_id=clean_task, execution_date=20240327T192904, start_date=20240327T193014, end_date=20240327T193014
[2024-03-27 19:30:14,373] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-27 19:30:14,411] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
